# Generated by Django 4.1.5 on 2023-03-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qoshiq',
            old_name='tugilgan_yil',
            new_name='sana',
        ),
    ]
