# Generated by Django 4.1.5 on 2023-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_tugilgan_yil_qoshiq_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoshiq',
            name='fayl',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
