# Generated by Django 4.1.5 on 2023-03-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_qoshiq_fayl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qoshiq',
        ),
    ]
